/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import java.awt.Color;

/**
 *
 * @author EstudianteUC
 */
public class dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard1
     */
    public dashboard1() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new dashboard.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new dashboard.PanelRound();
        btnDash = new javax.swing.JLabel();
        btn2 = new dashboard.PanelRound();
        btnRepor = new javax.swing.JLabel();
        btn3 = new dashboard.PanelRound();
        btnTrans = new javax.swing.JLabel();
        btn4 = new dashboard.PanelRound();
        btnAjust = new javax.swing.JLabel();
        btn5 = new dashboard.PanelRound();
        btnSopor = new javax.swing.JLabel();
        btn7 = new dashboard.PanelRound();
        btnStart = new javax.swing.JLabel();
        bg1 = new dashboard.PanelRound();
        showDisp = new dashboard.PanelRound();
        txtDisp = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        compDash = new dashboard.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound3 = new dashboard.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        compDash1 = new dashboard.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelRound4 = new dashboard.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        compDash2 = new dashboard.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelRound5 = new dashboard.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        compDash3 = new dashboard.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRound6 = new dashboard.PanelRound();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelRound1 = new dashboard.PanelRound();
        txts12 = new javax.swing.JLabel();
        txts15 = new javax.swing.JLabel();
        txts16 = new javax.swing.JLabel();
        txts13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(245, 245, 245));
        header.setRoundBottomRight(60);
        header.setRoundTopRight(60);

        jLabel1.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Administrador");

        jLabel2.setFont(new java.awt.Font("Red Hat Display", 1, 20)); // NOI18N
        jLabel2.setText("KARINA RUEDA");

        btn.setBackground(new java.awt.Color(230, 230, 230));
        btn.setRoundBottomLeft(30);
        btn.setRoundBottomRight(30);
        btn.setRoundTopLeft(30);
        btn.setRoundTopRight(30);

        btnDash.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnDash.setForeground(new java.awt.Color(102, 102, 102));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDash.setText("DASHBOARD");
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLayout = new javax.swing.GroupLayout(btn);
        btn.setLayout(btnLayout);
        btnLayout.setHorizontalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLayout.setVerticalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn2.setBackground(new java.awt.Color(230, 230, 230));
        btn2.setRoundBottomLeft(30);
        btn2.setRoundBottomRight(30);
        btn2.setRoundTopLeft(30);
        btn2.setRoundTopRight(30);

        btnRepor.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnRepor.setForeground(new java.awt.Color(102, 102, 102));
        btnRepor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRepor.setText("REPORTE");
        btnRepor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn2Layout.createSequentialGroup()
                .addComponent(btnRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRepor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn3.setBackground(new java.awt.Color(230, 230, 230));
        btn3.setRoundBottomLeft(30);
        btn3.setRoundBottomRight(30);
        btn3.setRoundTopLeft(30);
        btn3.setRoundTopRight(30);

        btnTrans.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnTrans.setForeground(new java.awt.Color(102, 102, 102));
        btnTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTrans.setText("TRANSACCIONES");
        btnTrans.setToolTipText("");
        btnTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addComponent(btnTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn4.setBackground(new java.awt.Color(230, 230, 230));
        btn4.setRoundBottomLeft(30);
        btn4.setRoundBottomRight(30);
        btn4.setRoundTopLeft(30);
        btn4.setRoundTopRight(30);

        btnAjust.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnAjust.setForeground(new java.awt.Color(102, 102, 102));
        btnAjust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjust.setText("AJUSTES");
        btnAjust.setToolTipText("");
        btnAjust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn4Layout.createSequentialGroup()
                .addComponent(btnAjust, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjust, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn5.setBackground(new java.awt.Color(230, 230, 230));
        btn5.setRoundBottomLeft(30);
        btn5.setRoundBottomRight(30);
        btn5.setRoundTopLeft(30);
        btn5.setRoundTopRight(30);

        btnSopor.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnSopor.setForeground(new java.awt.Color(102, 102, 102));
        btnSopor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSopor.setText("SOPORTE");
        btnSopor.setToolTipText("");
        btnSopor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSopor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSoporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSoporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn5Layout.createSequentialGroup()
                .addComponent(btnSopor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSopor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn7.setBackground(new java.awt.Color(170, 0, 0));
        btn7.setRoundBottomLeft(30);
        btn7.setRoundBottomRight(30);
        btn7.setRoundTopLeft(30);
        btn7.setRoundTopRight(30);

        btnStart.setBackground(new java.awt.Color(170, 0, 0));
        btnStart.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStart.setText("INICIAR OPERACIONES");
        btnStart.setToolTipText("");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn7Layout = new javax.swing.GroupLayout(btn7);
        btn7.setLayout(btn7Layout);
        btn7Layout.setHorizontalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn7Layout.createSequentialGroup()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn7Layout.setVerticalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setRoundBottomLeft(30);
        bg1.setRoundBottomRight(30);
        bg1.setRoundTopLeft(30);
        bg1.setRoundTopRight(30);
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showDisp.setBackground(new java.awt.Color(102, 204, 0));
        showDisp.setRoundBottomLeft(20);
        showDisp.setRoundBottomRight(20);
        showDisp.setRoundTopLeft(20);
        showDisp.setRoundTopRight(20);

        javax.swing.GroupLayout showDispLayout = new javax.swing.GroupLayout(showDisp);
        showDisp.setLayout(showDispLayout);
        showDispLayout.setHorizontalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        showDispLayout.setVerticalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        bg1.add(showDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtDisp.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        txtDisp.setForeground(new java.awt.Color(51, 51, 51));
        txtDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisp.setText("Acceso Total   ");
        txtDisp.setToolTipText("");
        txtDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDispMouseClicked(evt);
            }
        });
        bg1.add(txtDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 50));

        jLabel12.setFont(new java.awt.Font("Red Hat Display", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cerrar Sesion");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Red Hat Display", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Bienvenida Karina.");

        jLabel4.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("INICIO");

        compDash.setBackground(new java.awt.Color(245, 245, 245));
        compDash.setRoundBottomLeft(60);
        compDash.setRoundBottomRight(60);
        compDash.setRoundTopLeft(60);
        compDash.setRoundTopRight(60);

        jLabel5.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel5.setText("RETIRA TUS GANANCIAS");

        jLabel6.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel6.setText("<html>Seras redirigido a la pagina web segura <br >de mercado pago, para realizar la operacion</html>");

        panelRound3.setBackground(new java.awt.Color(170, 0, 0));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        jLabel7.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Continuar");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compDashLayout = new javax.swing.GroupLayout(compDash);
        compDash.setLayout(compDashLayout);
        compDashLayout.setHorizontalGroup(
            compDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDashLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(compDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        compDashLayout.setVerticalGroup(
            compDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDashLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        compDash1.setBackground(new java.awt.Color(245, 245, 245));
        compDash1.setRoundBottomLeft(60);
        compDash1.setRoundBottomRight(60);
        compDash1.setRoundTopLeft(60);
        compDash1.setRoundTopRight(60);

        jLabel8.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel8.setText("FACTURACION");

        jLabel9.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel9.setText("<html>Seras redirigido a la pagina web segura <br >de mercado pago, para realizar la operacion</html>");

        panelRound4.setBackground(new java.awt.Color(170, 0, 0));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);

        jLabel10.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Continuar");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compDash1Layout = new javax.swing.GroupLayout(compDash1);
        compDash1.setLayout(compDash1Layout);
        compDash1Layout.setHorizontalGroup(
            compDash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(compDash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        compDash1Layout.setVerticalGroup(
            compDash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        compDash2.setBackground(new java.awt.Color(245, 245, 245));
        compDash2.setRoundBottomLeft(60);
        compDash2.setRoundBottomRight(60);
        compDash2.setRoundTopLeft(60);
        compDash2.setRoundTopRight(60);

        jLabel11.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel11.setText("CUENTA BANCARIA");

        jLabel13.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel13.setText("<html>Seras redirigido a la pagina web segura <br >de mercado pago, para realizar la operacion</html>");

        panelRound5.setBackground(new java.awt.Color(170, 0, 0));
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);

        jLabel14.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Continuar");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compDash2Layout = new javax.swing.GroupLayout(compDash2);
        compDash2.setLayout(compDash2Layout);
        compDash2Layout.setHorizontalGroup(
            compDash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(compDash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        compDash2Layout.setVerticalGroup(
            compDash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        compDash3.setBackground(new java.awt.Color(245, 245, 245));
        compDash3.setRoundBottomLeft(60);
        compDash3.setRoundBottomRight(60);
        compDash3.setRoundTopLeft(60);
        compDash3.setRoundTopRight(60);

        jLabel15.setFont(new java.awt.Font("Red Hat Display", 1, 18)); // NOI18N
        jLabel15.setText("REPORTE DEL DIA");

        jLabel16.setFont(new java.awt.Font("Red Hat Display", 0, 14)); // NOI18N
        jLabel16.setText("<html>Seras redirigido a la pagina web segura <br >de mercado pago, para realizar la operacion</html>");

        panelRound6.setBackground(new java.awt.Color(170, 0, 0));
        panelRound6.setRoundBottomLeft(30);
        panelRound6.setRoundBottomRight(30);
        panelRound6.setRoundTopLeft(30);
        panelRound6.setRoundTopRight(30);

        jLabel17.setFont(new java.awt.Font("Red Hat Display", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Continuar");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout compDash3Layout = new javax.swing.GroupLayout(compDash3);
        compDash3.setLayout(compDash3Layout);
        compDash3Layout.setHorizontalGroup(
            compDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compDash3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(compDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        compDash3Layout.setVerticalGroup(
            compDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compDash3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel18.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("Novedades de la Version 1.0 beta");

        panelRound1.setBackground(new java.awt.Color(245, 245, 245));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txts12.setBackground(new java.awt.Color(102, 102, 102));
        txts12.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts12.setForeground(new java.awt.Color(51, 51, 51));
        txts12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txts12.setText("Nombre:  Caja Rapida Belen");
        panelRound1.add(txts12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, 30));

        txts15.setBackground(new java.awt.Color(102, 102, 102));
        txts15.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts15.setForeground(new java.awt.Color(51, 51, 51));
        txts15.setText("Mercado Pago: No configurado");
        panelRound1.add(txts15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 220, 30));

        txts16.setBackground(new java.awt.Color(102, 102, 102));
        txts16.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts16.setForeground(new java.awt.Color(51, 51, 51));
        txts16.setText("DNI: 23456532");
        panelRound1.add(txts16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));

        txts13.setBackground(new java.awt.Color(102, 102, 102));
        txts13.setFont(new java.awt.Font("Red Hat Display", 1, 14)); // NOI18N
        txts13.setForeground(new java.awt.Color(51, 51, 51));
        txts13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txts13.setText("Acceso:  Total");
        panelRound1.add(txts13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 170, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(compDash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(compDash2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compDash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compDash1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(compDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(compDash2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(compDash1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(compDash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseEntered
        btn.setBackground(new Color(150, 150, 150));
        btnDash.setForeground(Color.white);
        
    }//GEN-LAST:event_btnDashMouseEntered

    private void btnDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseExited
        // PREDETERMINADO -- 
        btn.setBackground(new Color(230, 230, 230));
        btnDash.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnDashMouseExited

    private void btnReporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnReporMouseClicked

    private void btnReporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseEntered
        // Hover
        btn2.setBackground(new Color(150, 150, 150));
        btnRepor.setForeground(Color.white);
    }//GEN-LAST:event_btnReporMouseEntered

    private void btnReporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseExited
         // PREDETERMINADO -- 
        btn2.setBackground(new Color(230, 230, 230));
        btnRepor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnReporMouseExited

    private void btnTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseEntered
        // TODO add your handling code here:
        // Hover
        btn3.setBackground(new Color(150, 150, 150));
        btnTrans.setForeground(Color.white);
    }//GEN-LAST:event_btnTransMouseEntered

    private void btnAjustMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseExited
         // PREDETERMINADO -- 
        btn4.setBackground(new Color(230, 230, 230));
        btnAjust.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnAjustMouseExited

    private void btnSoporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseEntered

         // Hover
        btn5.setBackground(new Color(150, 150, 150));
        btnSopor.setForeground(Color.white);
    }//GEN-LAST:event_btnSoporMouseEntered

    private void btnSoporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseExited
         // PREDETERMINADO -- 
        btn5.setBackground(new Color(230, 230, 230));
        btnSopor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnSoporMouseExited

    private void btnTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseExited
        // PREDETERMINADO -- 
        btn3.setBackground(new Color(230, 230, 230));
        btnTrans.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnTransMouseExited

    private void btnAjustMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseEntered
        // Hover
        btn4.setBackground(new Color(150, 150, 150));
        btnAjust.setForeground(Color.white);
    }//GEN-LAST:event_btnAjustMouseEntered

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
        btn7.setBackground(new Color(220, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
        btn7.setBackground(new Color(170, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseExited

    private void txtDispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMouseClicked
        // TODO add your handling code here:
        editDisp venClose = new editDisp();
        venClose.setVisible(true);
    }//GEN-LAST:event_txtDispMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dashboard.PanelRound bg1;
    private dashboard.PanelRound btn;
    private dashboard.PanelRound btn2;
    private dashboard.PanelRound btn3;
    private dashboard.PanelRound btn4;
    private dashboard.PanelRound btn5;
    private dashboard.PanelRound btn7;
    private javax.swing.JLabel btnAjust;
    private javax.swing.JLabel btnDash;
    private javax.swing.JLabel btnRepor;
    private javax.swing.JLabel btnSopor;
    private javax.swing.JLabel btnStart;
    private javax.swing.JLabel btnTrans;
    private dashboard.PanelRound compDash;
    private dashboard.PanelRound compDash1;
    private dashboard.PanelRound compDash2;
    private dashboard.PanelRound compDash3;
    private dashboard.PanelRound header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private dashboard.PanelRound panelRound1;
    private dashboard.PanelRound panelRound3;
    private dashboard.PanelRound panelRound4;
    private dashboard.PanelRound panelRound5;
    private dashboard.PanelRound panelRound6;
    private dashboard.PanelRound showDisp;
    private javax.swing.JLabel txtDisp;
    private javax.swing.JLabel txts12;
    private javax.swing.JLabel txts13;
    private javax.swing.JLabel txts15;
    private javax.swing.JLabel txts16;
    // End of variables declaration//GEN-END:variables
}
