/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import java.awt.Color;

/**
 *
 * @author EstudianteUC
 */
public class dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard1
     */
    public dashboard1() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new dashboard.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new dashboard.PanelRound();
        btnDash = new javax.swing.JLabel();
        btn2 = new dashboard.PanelRound();
        btnRepor = new javax.swing.JLabel();
        btn3 = new dashboard.PanelRound();
        btnTrans = new javax.swing.JLabel();
        btn4 = new dashboard.PanelRound();
        btnAjust = new javax.swing.JLabel();
        btn5 = new dashboard.PanelRound();
        btnSopor = new javax.swing.JLabel();
        btn7 = new dashboard.PanelRound();
        btnStart = new javax.swing.JLabel();
        btn9 = new dashboard.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        bg1 = new dashboard.PanelRound();
        showDisp = new dashboard.PanelRound();
        txtDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(245, 245, 245));
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopRight(40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Gerente Belen");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setText("KARINA RUEDA");

        btn.setBackground(new java.awt.Color(230, 230, 230));
        btn.setRoundBottomLeft(20);
        btn.setRoundBottomRight(20);
        btn.setRoundTopLeft(20);
        btn.setRoundTopRight(20);

        btnDash.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnDash.setForeground(new java.awt.Color(102, 102, 102));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDash.setText("DASHBOARD");
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLayout = new javax.swing.GroupLayout(btn);
        btn.setLayout(btnLayout);
        btnLayout.setHorizontalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );
        btnLayout.setVerticalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn2.setBackground(new java.awt.Color(230, 230, 230));
        btn2.setRoundBottomLeft(20);
        btn2.setRoundBottomRight(20);
        btn2.setRoundTopLeft(20);
        btn2.setRoundTopRight(20);

        btnRepor.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnRepor.setForeground(new java.awt.Color(102, 102, 102));
        btnRepor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRepor.setText("REPORTE");
        btnRepor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn2Layout.createSequentialGroup()
                .addComponent(btnRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRepor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn3.setBackground(new java.awt.Color(230, 230, 230));
        btn3.setRoundBottomLeft(20);
        btn3.setRoundBottomRight(20);
        btn3.setRoundTopLeft(20);
        btn3.setRoundTopRight(20);

        btnTrans.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnTrans.setForeground(new java.awt.Color(102, 102, 102));
        btnTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTrans.setText("TRANSACCIONES");
        btnTrans.setToolTipText("");
        btnTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addComponent(btnTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn4.setBackground(new java.awt.Color(230, 230, 230));
        btn4.setRoundBottomLeft(20);
        btn4.setRoundBottomRight(20);
        btn4.setRoundTopLeft(20);
        btn4.setRoundTopRight(20);

        btnAjust.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAjust.setForeground(new java.awt.Color(102, 102, 102));
        btnAjust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjust.setText("AJUSTES");
        btnAjust.setToolTipText("");
        btnAjust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn4Layout.createSequentialGroup()
                .addComponent(btnAjust, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjust, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn5.setBackground(new java.awt.Color(230, 230, 230));
        btn5.setRoundBottomLeft(20);
        btn5.setRoundBottomRight(20);
        btn5.setRoundTopLeft(20);
        btn5.setRoundTopRight(20);

        btnSopor.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnSopor.setForeground(new java.awt.Color(102, 102, 102));
        btnSopor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSopor.setText("SOPORTE");
        btnSopor.setToolTipText("");
        btnSopor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSopor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSoporMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSoporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn5Layout.createSequentialGroup()
                .addComponent(btnSopor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSopor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn7.setBackground(new java.awt.Color(170, 0, 0));
        btn7.setRoundBottomLeft(20);
        btn7.setRoundBottomRight(20);
        btn7.setRoundTopLeft(20);
        btn7.setRoundTopRight(20);

        btnStart.setBackground(new java.awt.Color(170, 0, 0));
        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStart.setText("INICIAR OPERACIONES");
        btnStart.setToolTipText("");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn7Layout = new javax.swing.GroupLayout(btn7);
        btn7.setLayout(btn7Layout);
        btn7Layout.setHorizontalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn7Layout.createSequentialGroup()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn7Layout.setVerticalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setRoundBottomLeft(20);
        btn9.setRoundBottomRight(20);
        btn9.setRoundTopLeft(20);
        btn9.setRoundTopRight(20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CERRAR SESION");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn9Layout = new javax.swing.GroupLayout(btn9);
        btn9.setLayout(btn9Layout);
        btn9Layout.setHorizontalGroup(
            btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn9Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btn9Layout.setVerticalGroup(
            btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setRoundBottomLeft(40);
        bg1.setRoundBottomRight(40);
        bg1.setRoundTopLeft(40);
        bg1.setRoundTopRight(40);
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showDisp.setBackground(new java.awt.Color(0, 204, 51));
        showDisp.setRoundBottomLeft(20);
        showDisp.setRoundBottomRight(20);
        showDisp.setRoundTopLeft(20);
        showDisp.setRoundTopRight(20);

        javax.swing.GroupLayout showDispLayout = new javax.swing.GroupLayout(showDisp);
        showDisp.setLayout(showDispLayout);
        showDispLayout.setHorizontalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        showDispLayout.setVerticalGroup(
            showDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        bg1.add(showDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtDisp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDisp.setText("Activo");
        txtDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDispMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDispMousePressed(evt);
            }
        });
        bg1.add(txtDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseEntered
        btn.setBackground(new Color(150, 150, 150));
        btnDash.setForeground(Color.white);
        
    }//GEN-LAST:event_btnDashMouseEntered

    private void btnDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseExited
        // PREDETERMINADO -- 
        btn.setBackground(new Color(230, 230, 230));
        btnDash.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnDashMouseExited

    private void btnReporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnReporMouseClicked

    private void btnReporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseEntered
        // Hover
        btn2.setBackground(new Color(150, 150, 150));
        btnRepor.setForeground(Color.white);
    }//GEN-LAST:event_btnReporMouseEntered

    private void btnReporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporMouseExited
         // PREDETERMINADO -- 
        btn2.setBackground(new Color(230, 230, 230));
        btnRepor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnReporMouseExited

    private void btnTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseEntered
        // TODO add your handling code here:
        // Hover
        btn3.setBackground(new Color(150, 150, 150));
        btnTrans.setForeground(Color.white);
    }//GEN-LAST:event_btnTransMouseEntered

    private void btnAjustMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseExited
         // PREDETERMINADO -- 
        btn4.setBackground(new Color(230, 230, 230));
        btnAjust.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnAjustMouseExited

    private void btnSoporMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseEntered

         // Hover
        btn5.setBackground(new Color(150, 150, 150));
        btnSopor.setForeground(Color.white);
    }//GEN-LAST:event_btnSoporMouseEntered

    private void btnSoporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporMouseExited
         // PREDETERMINADO -- 
        btn5.setBackground(new Color(230, 230, 230));
        btnSopor.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnSoporMouseExited

    private void btnTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransMouseExited
        // PREDETERMINADO -- 
        btn3.setBackground(new Color(230, 230, 230));
        btnTrans.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnTransMouseExited

    private void btnAjustMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustMouseEntered
        // Hover
        btn4.setBackground(new Color(150, 150, 150));
        btnAjust.setForeground(Color.white);
    }//GEN-LAST:event_btnAjustMouseEntered

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
        btn7.setBackground(new Color(220, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
        btn7.setBackground(new Color(170, 0, 0));
        btnStart.setForeground(Color.white);
    }//GEN-LAST:event_btnStartMouseExited

    private void txtDispMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMouseEntered
        // TODO add your handling code here:
        txtDisp.setText("Editar");
        txtDisp.setForeground(Color.gray);
        showDisp.setBackground(Color.white);
    }//GEN-LAST:event_txtDispMouseEntered

    private void txtDispMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDispMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dashboard.PanelRound bg1;
    private dashboard.PanelRound btn;
    private dashboard.PanelRound btn1;
    private dashboard.PanelRound btn2;
    private dashboard.PanelRound btn3;
    private dashboard.PanelRound btn4;
    private dashboard.PanelRound btn5;
    private dashboard.PanelRound btn6;
    private dashboard.PanelRound btn7;
    private dashboard.PanelRound btn8;
    private dashboard.PanelRound btn9;
    private javax.swing.JLabel btnAjust;
    private javax.swing.JLabel btnDash;
    private javax.swing.JLabel btnRepor;
    private javax.swing.JLabel btnSopor;
    private javax.swing.JLabel btnStart;
    private javax.swing.JLabel btnTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private dashboard.PanelRound panelRound1;
    private dashboard.PanelRound showDisp;
    private javax.swing.JLabel textbtn1;
    private javax.swing.JLabel txtDisp;
    // End of variables declaration//GEN-END:variables
}
